/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ZalandoApiClient.Client;
using ZalandoApiClient.Api;
using ZalandoApiClient.Model;

namespace ZalandoApiClient.Test
{
    /// <summary>
    ///  Class for testing CategoriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CategoriesApiTests
    {
        private CategoriesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CategoriesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoriesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CategoriesApi
            //Assert.IsInstanceOfType(typeof(CategoriesApi), instance, "instance is a CategoriesApi");
        }

        
        /// <summary>
        /// Test CategoriesGet
        /// </summary>
        [Test]
        public void CategoriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> name = null;
            //string type = null;
            //string outlet = null;
            //string hidden = null;
            //string targetGroup = null;
            //List<string> key = null;
            //List<string> parentKey = null;
            //List<string> childKey = null;
            //List<string> suggestedFilter = null;
            //string page = null;
            //string pageSize = null;
            //string acceptLanguage = null;
            //List<string> fields = null;
            //var response = instance.CategoriesGet(name, type, outlet, hidden, targetGroup, key, parentKey, childKey, suggestedFilter, page, pageSize, acceptLanguage, fields);
            //Assert.IsInstanceOf<Categories> (response, "response is Categories");
        }
        
        /// <summary>
        /// Test CategoriesKeyGet
        /// </summary>
        [Test]
        public void CategoriesKeyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> key = null;
            //string acceptLanguage = null;
            //List<string> fields = null;
            //var response = instance.CategoriesKeyGet(key, acceptLanguage, fields);
            //Assert.IsInstanceOf<Category> (response, "response is Category");
        }
        
    }

}
