/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ZalandoApiClient.Model
{
    /// <summary>
    /// Zalando API Article Price Schema
    /// </summary>
    [DataContract]
    public partial class ArticlePrice :  IEquatable<ArticlePrice>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArticlePrice" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ArticlePrice() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ArticlePrice" /> class.
        /// </summary>
        /// <param name="Currency"> (required).</param>
        /// <param name="Value"> (required).</param>
        /// <param name="Formatted"> (required).</param>
        public ArticlePrice(string Currency = null, decimal? Value = null, string Formatted = null)
        {
            // to ensure "Currency" is required (not null)
            if (Currency == null)
            {
                throw new InvalidDataException("Currency is a required property for ArticlePrice and cannot be null");
            }
            else
            {
                this.Currency = Currency;
            }
            // to ensure "Value" is required (not null)
            if (Value == null)
            {
                throw new InvalidDataException("Value is a required property for ArticlePrice and cannot be null");
            }
            else
            {
                this.Value = Value;
            }
            // to ensure "Formatted" is required (not null)
            if (Formatted == null)
            {
                throw new InvalidDataException("Formatted is a required property for ArticlePrice and cannot be null");
            }
            else
            {
                this.Formatted = Formatted;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public string Currency { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public decimal? Value { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="formatted", EmitDefaultValue=false)]
        public string Formatted { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArticlePrice {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Formatted: ").Append(Formatted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ArticlePrice);
        }

        /// <summary>
        /// Returns true if ArticlePrice instances are equal
        /// </summary>
        /// <param name="other">Instance of ArticlePrice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArticlePrice other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Currency == other.Currency ||
                    this.Currency != null &&
                    this.Currency.Equals(other.Currency)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                ) && 
                (
                    this.Formatted == other.Formatted ||
                    this.Formatted != null &&
                    this.Formatted.Equals(other.Formatted)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Currency != null)
                    hash = hash * 59 + this.Currency.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                if (this.Formatted != null)
                    hash = hash * 59 + this.Formatted.GetHashCode();
                return hash;
            }
        }
    }

}
