/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ZalandoApiClient.Model
{
    /// <summary>
    /// Zalando API Brand Schema
    /// </summary>
    [DataContract]
    public partial class Brand :  IEquatable<Brand>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Brand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Brand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Brand" /> class.
        /// </summary>
        /// <param name="Key">The unique key for a brand (required).</param>
        /// <param name="Name">Name of the brand (required).</param>
        /// <param name="ShopUrl">The url of the brand within the Zalando web shop (required).</param>
        /// <param name="LogoUrl">The url of the brand logo within the Zalando web shop.</param>
        /// <param name="LogoLargeUrl">The url of the large brand logo within the Zalando web shop.</param>
        /// <param name="BrandFamily">BrandFamily.</param>
        public Brand(string Key = null, string Name = null, string ShopUrl = null, string LogoUrl = null, string LogoLargeUrl = null, BrandFamily BrandFamily = null)
        {
            // to ensure "Key" is required (not null)
            if (Key == null)
            {
                throw new InvalidDataException("Key is a required property for Brand and cannot be null");
            }
            else
            {
                this.Key = Key;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for Brand and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "ShopUrl" is required (not null)
            if (ShopUrl == null)
            {
                throw new InvalidDataException("ShopUrl is a required property for Brand and cannot be null");
            }
            else
            {
                this.ShopUrl = ShopUrl;
            }
            this.LogoUrl = LogoUrl;
            this.LogoLargeUrl = LogoLargeUrl;
            this.BrandFamily = BrandFamily;
        }
        
        /// <summary>
        /// The unique key for a brand
        /// </summary>
        /// <value>The unique key for a brand</value>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }
        /// <summary>
        /// Name of the brand
        /// </summary>
        /// <value>Name of the brand</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// The url of the brand within the Zalando web shop
        /// </summary>
        /// <value>The url of the brand within the Zalando web shop</value>
        [DataMember(Name="shopUrl", EmitDefaultValue=false)]
        public string ShopUrl { get; set; }
        /// <summary>
        /// The url of the brand logo within the Zalando web shop
        /// </summary>
        /// <value>The url of the brand logo within the Zalando web shop</value>
        [DataMember(Name="logoUrl", EmitDefaultValue=false)]
        public string LogoUrl { get; set; }
        /// <summary>
        /// The url of the large brand logo within the Zalando web shop
        /// </summary>
        /// <value>The url of the large brand logo within the Zalando web shop</value>
        [DataMember(Name="logoLargeUrl", EmitDefaultValue=false)]
        public string LogoLargeUrl { get; set; }
        /// <summary>
        /// Gets or Sets BrandFamily
        /// </summary>
        [DataMember(Name="brandFamily", EmitDefaultValue=false)]
        public BrandFamily BrandFamily { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Brand {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ShopUrl: ").Append(ShopUrl).Append("\n");
            sb.Append("  LogoUrl: ").Append(LogoUrl).Append("\n");
            sb.Append("  LogoLargeUrl: ").Append(LogoLargeUrl).Append("\n");
            sb.Append("  BrandFamily: ").Append(BrandFamily).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Brand);
        }

        /// <summary>
        /// Returns true if Brand instances are equal
        /// </summary>
        /// <param name="other">Instance of Brand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Brand other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Key == other.Key ||
                    this.Key != null &&
                    this.Key.Equals(other.Key)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.ShopUrl == other.ShopUrl ||
                    this.ShopUrl != null &&
                    this.ShopUrl.Equals(other.ShopUrl)
                ) && 
                (
                    this.LogoUrl == other.LogoUrl ||
                    this.LogoUrl != null &&
                    this.LogoUrl.Equals(other.LogoUrl)
                ) && 
                (
                    this.LogoLargeUrl == other.LogoLargeUrl ||
                    this.LogoLargeUrl != null &&
                    this.LogoLargeUrl.Equals(other.LogoLargeUrl)
                ) && 
                (
                    this.BrandFamily == other.BrandFamily ||
                    this.BrandFamily != null &&
                    this.BrandFamily.Equals(other.BrandFamily)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Key != null)
                    hash = hash * 59 + this.Key.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.ShopUrl != null)
                    hash = hash * 59 + this.ShopUrl.GetHashCode();
                if (this.LogoUrl != null)
                    hash = hash * 59 + this.LogoUrl.GetHashCode();
                if (this.LogoLargeUrl != null)
                    hash = hash * 59 + this.LogoLargeUrl.GetHashCode();
                if (this.BrandFamily != null)
                    hash = hash * 59 + this.BrandFamily.GetHashCode();
                return hash;
            }
        }
    }

}
