/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZalandoApiClient.Api;
using ZalandoApiClient.Model;
using ZalandoApiClient.Client;
using System.Reflection;

namespace ZalandoApiClient.Test
{
    /// <summary>
    ///  Class for testing ArticleUnit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArticleUnitTests
    {
        // TODO uncomment below to declare an instance variable for ArticleUnit
        //private ArticleUnit instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArticleUnit
            //instance = new ArticleUnit();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArticleUnit
        /// </summary>
        [Test]
        public void ArticleUnitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArticleUnit
            //Assert.IsInstanceOfType<ArticleUnit> (instance, "variable 'instance' is a ArticleUnit");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'OriginalPrice'
        /// </summary>
        [Test]
        public void OriginalPriceTest()
        {
            // TODO unit test for the property 'OriginalPrice'
        }
        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Test]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'Stock'
        /// </summary>
        [Test]
        public void StockTest()
        {
            // TODO unit test for the property 'Stock'
        }
        /// <summary>
        /// Test the property 'PartnerId'
        /// </summary>
        [Test]
        public void PartnerIdTest()
        {
            // TODO unit test for the property 'PartnerId'
        }

    }

}
