/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZalandoApiClient.Api;
using ZalandoApiClient.Model;
using ZalandoApiClient.Client;
using System.Reflection;

namespace ZalandoApiClient.Test
{
    /// <summary>
    ///  Class for testing ArticleReviewArticleSizeRatings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArticleReviewArticleSizeRatingsTests
    {
        // TODO uncomment below to declare an instance variable for ArticleReviewArticleSizeRatings
        //private ArticleReviewArticleSizeRatings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArticleReviewArticleSizeRatings
            //instance = new ArticleReviewArticleSizeRatings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArticleReviewArticleSizeRatings
        /// </summary>
        [Test]
        public void ArticleReviewArticleSizeRatingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArticleReviewArticleSizeRatings
            //Assert.IsInstanceOfType<ArticleReviewArticleSizeRatings> (instance, "variable 'instance' is a ArticleReviewArticleSizeRatings");
        }

        /// <summary>
        /// Test the property 'OVERALL'
        /// </summary>
        [Test]
        public void OVERALLTest()
        {
            // TODO unit test for the property 'OVERALL'
        }
        /// <summary>
        /// Test the property 'CHEST'
        /// </summary>
        [Test]
        public void CHESTTest()
        {
            // TODO unit test for the property 'CHEST'
        }
        /// <summary>
        /// Test the property 'SLEEVES'
        /// </summary>
        [Test]
        public void SLEEVESTest()
        {
            // TODO unit test for the property 'SLEEVES'
        }
        /// <summary>
        /// Test the property 'SHOULDERS'
        /// </summary>
        [Test]
        public void SHOULDERSTest()
        {
            // TODO unit test for the property 'SHOULDERS'
        }
        /// <summary>
        /// Test the property 'LENGTH'
        /// </summary>
        [Test]
        public void LENGTHTest()
        {
            // TODO unit test for the property 'LENGTH'
        }
        /// <summary>
        /// Test the property 'LEG_FIT'
        /// </summary>
        [Test]
        public void LEG_FITTest()
        {
            // TODO unit test for the property 'LEG_FIT'
        }
        /// <summary>
        /// Test the property 'SHOE_WIDTH'
        /// </summary>
        [Test]
        public void SHOE_WIDTHTest()
        {
            // TODO unit test for the property 'SHOE_WIDTH'
        }
        /// <summary>
        /// Test the property 'BOOTLEG_WIDTH'
        /// </summary>
        [Test]
        public void BOOTLEG_WIDTHTest()
        {
            // TODO unit test for the property 'BOOTLEG_WIDTH'
        }
        /// <summary>
        /// Test the property 'HIPS_OR_REAR'
        /// </summary>
        [Test]
        public void HIPS_OR_REARTest()
        {
            // TODO unit test for the property 'HIPS_OR_REAR'
        }
        /// <summary>
        /// Test the property 'CUP_SIZE'
        /// </summary>
        [Test]
        public void CUP_SIZETest()
        {
            // TODO unit test for the property 'CUP_SIZE'
        }
        /// <summary>
        /// Test the property 'CHEST_GIRTH'
        /// </summary>
        [Test]
        public void CHEST_GIRTHTest()
        {
            // TODO unit test for the property 'CHEST_GIRTH'
        }
        /// <summary>
        /// Test the property 'COLLAR_SIZE'
        /// </summary>
        [Test]
        public void COLLAR_SIZETest()
        {
            // TODO unit test for the property 'COLLAR_SIZE'
        }

    }

}
