/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZalandoApiClient.Api;
using ZalandoApiClient.Model;
using ZalandoApiClient.Client;
using System.Reflection;

namespace ZalandoApiClient.Test
{
    /// <summary>
    ///  Class for testing ArticleImage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArticleImageTests
    {
        // TODO uncomment below to declare an instance variable for ArticleImage
        //private ArticleImage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArticleImage
            //instance = new ArticleImage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArticleImage
        /// </summary>
        [Test]
        public void ArticleImageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArticleImage
            //Assert.IsInstanceOfType<ArticleImage> (instance, "variable 'instance' is a ArticleImage");
        }

        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Test]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ThumbnailHdUrl'
        /// </summary>
        [Test]
        public void ThumbnailHdUrlTest()
        {
            // TODO unit test for the property 'ThumbnailHdUrl'
        }
        /// <summary>
        /// Test the property 'SmallUrl'
        /// </summary>
        [Test]
        public void SmallUrlTest()
        {
            // TODO unit test for the property 'SmallUrl'
        }
        /// <summary>
        /// Test the property 'SmallHdUrl'
        /// </summary>
        [Test]
        public void SmallHdUrlTest()
        {
            // TODO unit test for the property 'SmallHdUrl'
        }
        /// <summary>
        /// Test the property 'MediumUrl'
        /// </summary>
        [Test]
        public void MediumUrlTest()
        {
            // TODO unit test for the property 'MediumUrl'
        }
        /// <summary>
        /// Test the property 'MediumHdUrl'
        /// </summary>
        [Test]
        public void MediumHdUrlTest()
        {
            // TODO unit test for the property 'MediumHdUrl'
        }
        /// <summary>
        /// Test the property 'LargeUrl'
        /// </summary>
        [Test]
        public void LargeUrlTest()
        {
            // TODO unit test for the property 'LargeUrl'
        }
        /// <summary>
        /// Test the property 'LargeHdUrl'
        /// </summary>
        [Test]
        public void LargeHdUrlTest()
        {
            // TODO unit test for the property 'LargeHdUrl'
        }

    }

}
