/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ZalandoApiClient.Client;
using ZalandoApiClient.Model;

namespace ZalandoApiClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBrandsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Shop Brands
        /// </summary>
        /// <remarks>
        /// Zalando API Brands Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Brands</returns>
        Brands BrandsGet (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null);

        /// <summary>
        /// Shop Brands
        /// </summary>
        /// <remarks>
        /// Zalando API Brands Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>ApiResponse of Brands</returns>
        ApiResponse<Brands> BrandsGetWithHttpInfo (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null);
        /// <summary>
        /// Get Single Brand by Key
        /// </summary>
        /// <remarks>
        /// Zalando API Brand Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Brand</returns>
        Brand BrandsKeyGet (string key, string acceptLanguage = null, List<string> fields = null);

        /// <summary>
        /// Get Single Brand by Key
        /// </summary>
        /// <remarks>
        /// Zalando API Brand Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>ApiResponse of Brand</returns>
        ApiResponse<Brand> BrandsKeyGetWithHttpInfo (string key, string acceptLanguage = null, List<string> fields = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Shop Brands
        /// </summary>
        /// <remarks>
        /// Zalando API Brands Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of Brands</returns>
        System.Threading.Tasks.Task<Brands> BrandsGetAsync (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null);

        /// <summary>
        /// Shop Brands
        /// </summary>
        /// <remarks>
        /// Zalando API Brands Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of ApiResponse (Brands)</returns>
        System.Threading.Tasks.Task<ApiResponse<Brands>> BrandsGetAsyncWithHttpInfo (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null);
        /// <summary>
        /// Get Single Brand by Key
        /// </summary>
        /// <remarks>
        /// Zalando API Brand Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of Brand</returns>
        System.Threading.Tasks.Task<Brand> BrandsKeyGetAsync (string key, string acceptLanguage = null, List<string> fields = null);

        /// <summary>
        /// Get Single Brand by Key
        /// </summary>
        /// <remarks>
        /// Zalando API Brand Schema
        /// </remarks>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of ApiResponse (Brand)</returns>
        System.Threading.Tasks.Task<ApiResponse<Brand>> BrandsKeyGetAsyncWithHttpInfo (string key, string acceptLanguage = null, List<string> fields = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BrandsApi : IBrandsApi
    {
        private ZalandoApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BrandsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BrandsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = ZalandoApiClient.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BrandsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BrandsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ZalandoApiClient.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ZalandoApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Shop Brands Zalando API Brands Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Brands</returns>
        public Brands BrandsGet (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null)
        {
             ApiResponse<Brands> localVarResponse = BrandsGetWithHttpInfo(key, name, brandFamilyName, brandFamilyKey, page, pageSize, acceptLanguage, fields);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Shop Brands Zalando API Brands Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>ApiResponse of Brands</returns>
        public ApiResponse< Brands > BrandsGetWithHttpInfo (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null)
        {

            var localVarPath = "/brands";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (key != null) localVarQueryParams.Add("key", Configuration.ApiClient.ParameterToString(key)); // query parameter
            if (name != null) localVarQueryParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // query parameter
            if (brandFamilyName != null) localVarQueryParams.Add("brandFamilyName", Configuration.ApiClient.ParameterToString(brandFamilyName)); // query parameter
            if (brandFamilyKey != null) localVarQueryParams.Add("brandFamilyKey", Configuration.ApiClient.ParameterToString(brandFamilyKey)); // query parameter
            if (page != null) localVarQueryParams.Add("page", Configuration.ApiClient.ParameterToString(page)); // query parameter
            if (pageSize != null) localVarQueryParams.Add("pageSize", Configuration.ApiClient.ParameterToString(pageSize)); // query parameter
            if (fields != null) localVarQueryParams.Add("fields", Configuration.ApiClient.ParameterToString(fields)); // query parameter
            if (acceptLanguage != null) localVarHeaderParams.Add("Accept-Language", Configuration.ApiClient.ParameterToString(acceptLanguage)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("BrandsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Brands>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Brands) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Brands)));
            
        }

        /// <summary>
        /// Shop Brands Zalando API Brands Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of Brands</returns>
        public async System.Threading.Tasks.Task<Brands> BrandsGetAsync (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null)
        {
             ApiResponse<Brands> localVarResponse = await BrandsGetAsyncWithHttpInfo(key, name, brandFamilyName, brandFamilyKey, page, pageSize, acceptLanguage, fields);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Shop Brands Zalando API Brands Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">Request Brand by key (optional)</param>
        /// <param name="name">Request Brand by name (optional)</param>
        /// <param name="brandFamilyName">Request Brand by brandFamilyName (optional)</param>
        /// <param name="brandFamilyKey">Request Brand by brandFamilyKey (optional)</param>
        /// <param name="page">to request with required page number or pagination (optional)</param>
        /// <param name="pageSize">to request with required page size in a page (optional)</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of ApiResponse (Brands)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Brands>> BrandsGetAsyncWithHttpInfo (List<string> key = null, List<string> name = null, List<string> brandFamilyName = null, List<string> brandFamilyKey = null, string page = null, string pageSize = null, string acceptLanguage = null, List<string> fields = null)
        {

            var localVarPath = "/brands";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (key != null) localVarQueryParams.Add("key", Configuration.ApiClient.ParameterToString(key)); // query parameter
            if (name != null) localVarQueryParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // query parameter
            if (brandFamilyName != null) localVarQueryParams.Add("brandFamilyName", Configuration.ApiClient.ParameterToString(brandFamilyName)); // query parameter
            if (brandFamilyKey != null) localVarQueryParams.Add("brandFamilyKey", Configuration.ApiClient.ParameterToString(brandFamilyKey)); // query parameter
            if (page != null) localVarQueryParams.Add("page", Configuration.ApiClient.ParameterToString(page)); // query parameter
            if (pageSize != null) localVarQueryParams.Add("pageSize", Configuration.ApiClient.ParameterToString(pageSize)); // query parameter
            if (fields != null) localVarQueryParams.Add("fields", Configuration.ApiClient.ParameterToString(fields)); // query parameter
            if (acceptLanguage != null) localVarHeaderParams.Add("Accept-Language", Configuration.ApiClient.ParameterToString(acceptLanguage)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("BrandsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Brands>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Brands) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Brands)));
            
        }

        /// <summary>
        /// Get Single Brand by Key Zalando API Brand Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Brand</returns>
        public Brand BrandsKeyGet (string key, string acceptLanguage = null, List<string> fields = null)
        {
             ApiResponse<Brand> localVarResponse = BrandsKeyGetWithHttpInfo(key, acceptLanguage, fields);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Single Brand by Key Zalando API Brand Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>ApiResponse of Brand</returns>
        public ApiResponse< Brand > BrandsKeyGetWithHttpInfo (string key, string acceptLanguage = null, List<string> fields = null)
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new ApiException(400, "Missing required parameter 'key' when calling BrandsApi->BrandsKeyGet");

            var localVarPath = "/brands/{key}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (key != null) localVarPathParams.Add("key", Configuration.ApiClient.ParameterToString(key)); // path parameter
            if (fields != null) localVarQueryParams.Add("fields", Configuration.ApiClient.ParameterToString(fields)); // query parameter
            if (acceptLanguage != null) localVarHeaderParams.Add("Accept-Language", Configuration.ApiClient.ParameterToString(acceptLanguage)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("BrandsKeyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Brand>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Brand) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Brand)));
            
        }

        /// <summary>
        /// Get Single Brand by Key Zalando API Brand Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of Brand</returns>
        public async System.Threading.Tasks.Task<Brand> BrandsKeyGetAsync (string key, string acceptLanguage = null, List<string> fields = null)
        {
             ApiResponse<Brand> localVarResponse = await BrandsKeyGetAsyncWithHttpInfo(key, acceptLanguage, fields);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Single Brand by Key Zalando API Brand Schema
        /// </summary>
        /// <exception cref="ZalandoApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">To get unique Brand by key.</param>
        /// <param name="acceptLanguage">choose shop (country and language) (optional)</param>
        /// <param name="fields">Comma separated list of fields that should be returned. Fields of subobjects are specified with dots as separator. Fields of objects within lists are specified in the same way.  Example: id,name,brand.key,brand.name, units.id,units.size,units.price.formatted (optional)</param>
        /// <returns>Task of ApiResponse (Brand)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Brand>> BrandsKeyGetAsyncWithHttpInfo (string key, string acceptLanguage = null, List<string> fields = null)
        {
            // verify the required parameter 'key' is set
            if (key == null)
                throw new ApiException(400, "Missing required parameter 'key' when calling BrandsApi->BrandsKeyGet");

            var localVarPath = "/brands/{key}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (key != null) localVarPathParams.Add("key", Configuration.ApiClient.ParameterToString(key)); // path parameter
            if (fields != null) localVarQueryParams.Add("fields", Configuration.ApiClient.ParameterToString(fields)); // query parameter
            if (acceptLanguage != null) localVarHeaderParams.Add("Accept-Language", Configuration.ApiClient.ParameterToString(acceptLanguage)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("BrandsKeyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Brand>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Brand) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Brand)));
            
        }

    }
}
